#162235868 Create view endpoints for red flags
Curti-s/ireporter-api pull request #12
Opened 2018-11-28 08:33 UTC by Curti-s

### What does this PR do?
It ensures that there are view endpoints for red flags 

### Description of the completed task
Created the following endpoints:
- POST request for new red flag creation
- GET request for a particular red flag
- GET request for all red flags
- PUT request for a particular red flag
- DELETE request for a particular red flag

### How can this be manually tested
Source the .env file and run the flask app [flask run]
Define a collection in postman and perform GET POST PUT and DELETE request operations

### Screenshots
![screenshot from 2018-11-28 11-30-00](https://user-images.githubusercontent.com/19207575/49138845-5fa58500-f301-11e8-8771-1771595f2ad9.png)
![screenshot from 2018-11-28 11-30-31](https://user-images.githubusercontent.com/19207575/49138854-63d1a280-f301-11e8-9056-0c79ede17df1.png)
![screenshot from 2018-11-28 11-30-43](https://user-images.githubusercontent.com/19207575/49138863-67fdc000-f301-11e8-9009-5f03a132ffd5.png)

### Relevant pivotal tracker stories
 #162235868

2018-12-02 18:25 UTC, thoth-ky requested changes
Kindly work on the feedback I have given you. Use data provided by user, do not hardcode. Also ensure you write tests for this feature

2018-12-02 18:25 UTC, thoth-ky commented on app/__init__.py
> +from .api.v1.views import redflag as rf
Names should be meaningful to aid in readability and documentation of code
```suggestion
from .api.v1.views import redflag
```

2018-12-02 18:25 UTC, thoth-ky commented on app/api/v1/views/redflag_view.py
> +    def post(self):
This method does not seem to be using payload from the request.

2018-12-05 11:43 UTC, Curti-s commented on app/api/v1/views/redflag_view.py
> +    def post(self):
`Sure. I will refactor. Thanks for the feedback

2018-12-05 18:14 UTC, merged