#162263189 Define endpoints for redflags
Curti-s/ireporter-api pull request #13
Opened 2018-11-28 22:30 UTC by Curti-s

### What does this PR do?
It ensures that tests are created for the CRUD operations on red flags

### Description of the task completed
Define test for GET, PUT, POST and DELETE

### How can this be manually tested?
Run pytest

### Screenshot
![screenshot from 2018-11-29 01-29-08](https://user-images.githubusercontent.com/19207575/49186662-4e4a9000-f376-11e8-98f6-677c4f5479bf.png)
![screenshot from 2018-11-29 01-29-13](https://user-images.githubusercontent.com/19207575/49186670-51458080-f376-11e8-97da-6204a372faa0.png)
![screenshot from 2018-11-29 01-29-15](https://user-images.githubusercontent.com/19207575/49186672-54407100-f376-11e8-8c67-9e3f17939d75.png)

### Relevant pivotal tracker stories
#162263189

2018-12-02 18:30 UTC, thoth-ky requested changes
Kindly check out my suggestions and implement the feedback.

2018-12-02 18:30 UTC, jmutuku95 commented on .gitignore
> +__pycache__/
Add `.coverage` to gitignore

2018-12-02 18:30 UTC, jmutuku95 commented on .travis.yml
> +  - pip install python-coveralls
Add these to the requirements file so you do not have to `pip install ` each

2018-12-02 18:30 UTC, jmutuku95 commented on app/api/v1/views/redflag_view.py
> +    # # edit a red flag comment / locaion
Remove any commented code

2018-12-02 18:30 UTC, jmutuku95 commented on tests/v1/test_redflag.py
> +    # def test_edit_a_redflag(self):
Remove commented code

2018-12-02 18:31 UTC, jmutuku95 commented
your PR title doesn't exactly match what you say it does. Try separate concerns and have different PRs for different concerns

2018-12-05 09:35 UTC, Curti-s commented
Will do so


On Sun, Dec 2, 2018 at 9:31 PM Joseph Mutuku Kyalo <notifications@github.com>
wrote:

> your PR title doesn't exactly match what you say it does. Try separate
> concerns and have different PRs for different concerns
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Curti-s/iReporter/pull/13#issuecomment-443530837>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ASUVl4ruwqEIV_UJYGmnzzZI33sR_mxlks5u1ByMgaJpZM4Y4j_f>
> .
>

2018-12-05 18:14 UTC, merged